### ISSUE TITLE
Detection fails for share install on Amazon Linux

### ISSUE THREAD

**Issue by ilataniuk** [PerlAlien/Alien-pkgconf#15]
During install on the Macbook with M1 processor got:

perl-5.18.4/bin/perl" script/probe.pl site perl-5.18.4/lib/5.18.4/aarch64-linux perl-5.18.4/lib/site_perl/5.18.4/aarch64-linux
do not know enough about this OS to probe for correct paths. 

Please open a ticket https://github.com/PerlAlien/Alien-pkgconf

**Comment by plicease** [comment]
`aarch64-linux` suggests that you are running Linux in a VM or under docker?  Do you know which distro it is?  So far we have detection logic for Gentoo, Alpine and Debian.

**Comment by ilataniuk** [comment]
> `aarch64-linux` suggests that you are running Linux in a VM or under docker? Do you know which distro it is? So far we have detection logic for Gentoo, Alpine and Debian.

You're right, under docker.
FROM
docker/amazonlinux

**Comment by plicease** [comment]
Amazon Linux appears to just be a clone of RedHat EL, but the detection logic wasn't recognizing it.  I've updated this in 0.19 and it worked for me locally at least on a AL2 docker container.  Please let me know if it doesn't work for you.

**Comment by ilataniuk** [comment]
Thx! We also made fix via symlink to redhat:

`ln -s /etc/os-release /etc/redhat-release`
