### ISSUE TITLE
Investigagte 5.18 + 5.16 failure

### ISSUE THREAD

**Issue by plicease** [PerlAlien/Alien-pkgconf#6]
I added a skip on 5.16 and 5.18 in CI because it started failing, I think when I switched to cip.

bbcf75bebbefda91c17b06a6945b7725c2524162

These fails are not showing up in cpantesters, so it is either a prereq fail or something wrong with the CI itself.

**Comment by thibaultduponchelle** [comment]
What I can say here is : 
The timeout occurs with prereqs version from the core distribution, if the prereqs are updated well (should be done by https://github.com/plicease/cip/blob/master/bin/cip#L264 with cpanm using Makefile.PL file I guess) then the problem disappears (at least I tested on perl 5.18.4)

**Comment by plicease** [comment]
Thanks for investigating this.  I think we want to bump the EUMM prereq in the configure phase for now, and punt on a proper fix for CI.
